### ISSUE TITLE
Endianness

### ISSUE THREAD

**Issue by marekkokot** [Kmer-File-Format/kff-tools#4]
Hi,

there is
```
template<typename T>
void write_value(T val, fstream & fs) {
	fs.write((char*)&val, sizeof(T));
}
template<typename T>
void read_value(T & val, fstream & fs) {
	fs.read((char*)&val, sizeof(T));
}
``` 
in kff_io.cpp

Shouldn't it be implemented differently to force appropriate endianness? (big-endian according to https://github.com/Kmer-File-Format/kff-reference)

Here is my implementation if you want:
```
template<typename T>
void StoreBigEndian(uint8_t* buff, const T& data)
{
	for (int32_t b = sizeof(data) - 1; b >= 0; --b)
		*buff++ = data >> (8 * b);
}

```
and usage example:
```
uint32_t free_size = 0;
std::vector<uint8_t> tmp(sizeof(uint32_t));
StoreBigEndian(tmp.data(), free_size);
fwrite(tmp.data(), 1, sizeof(free_size), file);
```
Probably not the cleanest code in the world :) Also, I am not sure about its performance.

**Comment by yoann-dufresne** [comment]
Thanks Marek to pointing it to me.
You are totally right, it is a bug not triggered on my system.

I will correct it in the API repository https://github.com/Kmer-File-Format/kff-cpp-api
It should be included here in a few hours/days
